# Generated by Django 5.2.3 on 2025-06-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee')], max_length=20),
        ),
    ]
